name: "Simply Web Deploy"
description: "Deploy projects with Web Deploy"

inputs:
  action:
    description: "Action fetch/deploy/fetch&deploy"
    default: 'deploy'
  sync-action:
    description: "Action to run for syncronization"
    required: false
    default: '""'
  website-name:
    description: "IIS website name"
    required: true
  server-computer-name:
    description: "IIS server computer name"
    required: true
  server-username:
    description: "IIS server username"
    required: true
  server-password:
    description: "IIS server password"
    required: true
  source-path:
    description: "The source directory for payload"
    required: false
    default: '\publish\'
  target-path:
    description: "The target directory for payload"
    required: false
    default: '""'
  target-delete:
    description: "Delete files on the destination computer that do not exist on the source computer"
    required: false
    default: "false"
  skip-directory-paths:
    description: "Comma-separated list of directories to skip during deployment"
    required: false
    default: '""'
  skip-files:
    description: "Comma-separated list of specific files to skip during deployment"
    required: false
    default: '""'
  skip-patterns:
    description: "Comma-separated list of regex patterns to skip during deployment"
    required: false
    default: '""'

runs:
  using: "composite"
  steps:
    - name: Stop Application Pool
      shell: pwsh
      run: >
        ${{ github.action_path }}/Scripts/Set-ApplicationPool.ps1
        StopAppPool
        ${{ inputs.website-name }}
        ${{ inputs.server-computer-name }}
        ${{ inputs.server-username }}
        ${{ inputs.server-password }}

    - name: Fetch Application
      shell: pwsh
      if: ${{ contains(inputs.action, 'fetch') }}
      run: >
        ${{ github.action_path }}/Scripts/Fetch-ApplicationPackage.ps1
        ${{ inputs.source-path }}
        ${{ inputs.target-path }}
        ${{ inputs.website-name }}
        ${{ inputs.server-computer-name }}
        ${{ inputs.server-username }}
        ${{ inputs.server-password }}
        ${{ inputs.target-delete }}
        ${{ inputs.skip-directory-paths }}
        ${{ inputs.skip-files }}
        ${{ inputs.skip-patterns }}
        
    - name: Sync Action
      if: ${{ inputs.sync-action!="" }}
      run: ${{ inputs.sync-action }}
      
    - name: Deploy Application
      shell: pwsh
      if: ${{ contains(inputs.action, 'deploy') }}
      run: >
        ${{ github.action_path }}/Scripts/Deploy-ApplicationPackage.ps1
        ${{ inputs.source-path }}
        ${{ inputs.target-path }}
        ${{ inputs.website-name }}
        ${{ inputs.server-computer-name }}
        ${{ inputs.server-username }}
        ${{ inputs.server-password }}
        ${{ inputs.target-delete }}
        ${{ inputs.skip-directory-paths }}
        ${{ inputs.skip-files }}
        ${{ inputs.skip-patterns }}
      
    - name: Start Application Pool
      shell: pwsh
      run: >
        ${{ github.action_path }}/Scripts/Set-ApplicationPool.ps1
        StartAppPool
        ${{ inputs.website-name }}
        ${{ inputs.server-computer-name }}
        ${{ inputs.server-username }}
        ${{ inputs.server-password }}

branding:
  icon: "upload-cloud"
  color: "purple"
